name: Test documentation build

on:
  pull_request:
    paths:
      - '**.py'
      - '**.ipynb'
      - '**.rst'
      - '**.md'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Run a one-line script
      run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
    - name: checkout
      uses: actions/checkout@v7
      with:
        fetch-depth: 0

    - name: Setup Micromamba
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-name: TEST
        init-shell: bash
        create-args: >-
          python=3.12 pip
          --file requirements-dev.txt
          --channel conda-forge

    - name: Install caldip
      shell: bash -l {0}
      run: |
        pip install --only-binary=matplotlib -e .

    - name: Build documentation
      shell: bash -l {0}
      run: |
        set -e
        # jupyter nbconvert --to notebook --execute notebooks/demo.ipynb --output=demo-output.ipynb --ExecutePreprocessor.allow_errors=False
        # mv notebooks/*output.ipynb docs/source/
        pushd docs
        make clean && make html
        popd
