name: Publish to PyPI

on:
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Clean repository before build
        run: git clean -fxd

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip wheel setuptools build twine

      - name: Build package
        run: python -m build --sdist --wheel . --outdir dist

      - name: Check built distributions
        run: python -m twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
